language: cpp

branches:
  only:
  - "/^master$/"
  - "/^pre-release$/"

cache: ccache

compiler:
- gcc

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-6

install:
- "[ $CC = gcc ] && export CC=gcc-6 || true"
- "[ $CXX = g++ ] && export CXX=g++-6 || true"

script:
- mkdir -p build && cd build && cmake .. && make && make test

notifications:
  email:
    on_success: never
    on_failure: never
  slack:
    secure: ZWlERbAY+tbPRdjWajoUJYxKtI4VxaB/Cof3xHTJ07KJuPESs2o9yXN2p5WZy2f0CpscZQnFYxL6kdwADK0e6A964cK39gdz7dgfEoGKQpzrzoTIWzNNg1h1kZ0uA44BD4/KqXjWaxv5zCUYfl4BTTl/mDdXD0E0TUayyb1oAfqdDr0ONW/Z+qgJUAFENtBB4BE2YoAR20cdyhc6NyP6xKZ4QGQLNslFWiDUmJxNQ/oXb26Q9Y7y5lBaNuYNwXozg8qNylSZiD9io7QqvjS6UJcKRKeuH94nzjNf7f7aE5yCWLgKxP7dMNq0/sdvZG86k/oUMC+2POvKnGJmxnIehEK3Af9CeUbzF8rSVs0FFYxHABxmo9ADkkukzmiZNrIhpcloorkl1nbQ27nMWZYpOwzVF5X/GliJZG9O9SwDMrJUyPGtaYRzpYS++SrHniO1ltEXprG28DSZ9O90k3Y73MgxUxjcQRDn2k4Nj44AIARI57vlEPxa6mqBeTm5An1VKGZEeOHfwlmKls4ZcGuLF7U5eeSYEKIle3eIwy8mtL/6eNv629G1+mUdHmTG3j9MP7gt3w25gdR+cMUIBKOSIoHkBWMkdhVystke4ib/ZFB0ibN2cUpPeXSFzE5k58rLZkYJoDkg4IXHahFNRgNHCkTlf3TJklF5Vn19vDTjzGk=
